server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oziggydrumz/employee-config-repo
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: true
          management:
            endpoints:
              web:
                exposure:
                  include: "*"



          logging:
            level:
              org.springframework.cloud.config.server: DEBUG
              default-label: main





